#chrome parameter 
chrome:
  #導向頁面的最多等待時間。(毫秒)
  wait_for_timeout: 50000
  #強制等待時間。(秒)
  pre-waiting-time: 10
  chrome_show : True

block_setting:
  blocked_types: 
    - image
    - font
    - media
    - stylesheet
  ad_domains: 
    - google-analytics.com
    - doubleclick.net
    - adsystem.com
  
downloader_setting:
  #設定線程數，太慢或被鎖時可調整
  thread_count: 8

  download_mode: "--auto-select"
  retry-count: 10

url:
  5278_site: "https://5278.cc"